#!/bin/bash
set -e

# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
#     CREATE USER one WITH ENCRYPTED PASSWORD 'one_DOCKER';
#     GRANT USAGE ON SCHEMA public to one;
#     ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO one;
#     CREATE DATABASE db WITH OWNER "one" ENCODING 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C.UTF-8' TEMPLATE template0;
#     GRANT ALL PRIVILEGES ON DATABASE db TO one;
#
#     \c db
#     ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO one;
#     GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO one;
#     GRANT ALL ON ALL TABLES IN SCHEMA public TO one;
# EOSQL
